services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 83:80
        env_file:
            - .env
        volumes:
            - ".:/var/www/html"
            - ./public/assets/img:/var/www/html/public/assets/img

    worker:
        image: corpen-app
        env_file:
            - .env
        volumes:
            - ".:/var/www/html"
            - ./public/assets/img:/var/www/html/public/assets/img
        command: php artisan queue:work database --queue=default --timeout=1800 --tries=3 --memory=512 -vvv
        restart: unless-stopped
